version: "3.8"

networks:
  poznejpovolani-network:
    driver: bridge

services:
  symfony:
    image: php:8.2.4-fpm # Use PHP 8.2.4 image
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      # Add any other environment variables needed for Symfony
    networks:
      - poznejpovolani-network
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: popo2425
    ports:
      - 3306:3306
    networks:
      - poznejpovolani-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - poznejpovolani-network