version: '3.8'

networks:
  symfony_popo-network:
    external: true

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - symfony_popo-network

  dev:
    build:
      context: ./
      target: dev
    ports:
      - '8081:8081'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - redis
    restart: always
    networks:
      - symfony_popo-network

  prod:
    build:
      context: ./
      target: production
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8082:8082'
    command: npm run start
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    restart: always
    networks:
      - symfony_popo-network
